# Print available commands
default:
    @just --list

# Initialize workspace modules (all, backend, or web)
init module="all":
    #!/usr/bin/env bash
    set -euo pipefail
    source ./scripts/_lib.sh
    target=$(resolve_module "{{ module }}") || exit $?

    if should_run "$target" "backend"; then
        echo "Initializing Python backend workspace..."
        uv sync --all-packages --all-extras
    fi

    if should_run "$target" "web"; then
        path=$(resolve_module_path "web")
        echo "Initializing React frontend ($path)..."
        npm --prefix "$path" install
    fi

# Backward-compatible alias for documentation and older workflows
init-dev:
    @just init all

# Run linters and formatters (all, backend, or web)
lint module="all":
    #!/usr/bin/env bash
    set -euo pipefail
    source ./scripts/_lib.sh
    target=$(resolve_module "{{ module }}") || exit $?

    if should_run "$target" "backend"; then
        echo "Linting Python codebase..."
        uv run ruff format
        uv run ruff check --fix
    fi

    if should_run "$target" "web"; then
        path=$(resolve_module_path "web")
        echo "Linting React frontend ($path)..."
        # Optional: Add eslint/formatter check here once configured
        echo "React frontend formatting is integrated."
    fi

# Run static type checks (all, backend, or web)
check module="all":
    #!/usr/bin/env bash
    set -euo pipefail
    source ./scripts/_lib.sh
    target=$(resolve_module "{{ module }}") || exit $?

    if should_run "$target" "backend"; then
        echo "Type checking Python backend..."
        uv run pyright
    fi

    if should_run "$target" "web"; then
        path=$(resolve_module_path "web")
        echo "Compiling and type checking React frontend ($path)..."
        npm --prefix "$path" run build
    fi

# Run server for a specific module or all in development mode (backend, web, or all)
dev module="all":
    @bash ./scripts/dev-run.sh "{{ module }}"

# Run Python tests from pyproject testpaths. Can specify target paths (e.g. just test packages/rag-core/tests/unit)
test +paths="":
    @bash ./scripts/run-tests.sh {{ paths }}

# Kill any dangling development servers (FastAPI on 8389, Vite on 5173)
kill:
    @bash ./scripts/kill-dev.sh

# Open the web UI in the browser
browser:
    @bash ./scripts/open-browser.sh

# Start the background worker for async document processing
worker:
    @bash ./scripts/worker-run.sh

# Generate OpenAPI client for the frontend UI module from Python backend schema
gen-ui-api:
    @bash ./scripts/gen-ui-api.sh

# Start backend services in CPU mode (Default / macOS). Can specify multiple profiles (e.g. just up docling marker)
up +profiles="":
    @bash ./scripts/compose-up.sh cpu {{ profiles }}

# Start backend services in GPU mode (WSL / Linux). Can specify multiple profiles (e.g. just up-gpu docling marker)
up-gpu +profiles="":
    @bash ./scripts/compose-up.sh gpu {{ profiles }}

# Stop all backend services
down:
    docker compose -p rag -f infra/services/docker-compose.yml -f infra/services/docker-compose.gpu.yml down --remove-orphans


# Start local model serving (Ollama & TEI). Can specify multiple models (e.g. just models-up embed,rerank)
models-up +models="all":
    @bash ./scripts/models-up.sh {{ models }}

# Stop local model serving (Ollama & TEI)
models-down:
    docker compose -f infra/models/docker-compose.yml down --remove-orphans

# Run database migrations to upgrade schema
db-upgrade revision="head":
    @uv --directory apps/backend run alembic upgrade {{ revision }}

# Rollback database migrations
db-downgrade revision="-1":
    @uv --directory apps/backend run alembic downgrade {{ revision }}

# Generate a new autogenerated database migration script
db-migrate message:
    @uv --directory apps/backend run alembic revision --autogenerate -m "{{ message }}"

# View database migration history
db-history:
    @uv --directory apps/backend run alembic history
