[project]
name = "rag-experiment-api"
version = "0.1.0"
description = "FastAPI app for parsing and chunking APIs"
requires-python = ">=3.13"
dependencies = [
    "app-layer-base",
    "fastapi>=0.115.0",
    "taskiq>=0.11.0",
    "taskiq-redis>=1.0.0",
    "taskiq-fastapi>=0.3.0",
    "taskiq-aio-pika>=0.4.0",
    "pydantic>=2.9.0",
    "pydantic-settings>=2.6.0",
    "python-multipart>=0.0.12",
    "rag-core",
    "uvicorn[standard]>=0.34.0",
]

[tool.uv]
package = false

[tool.uv.sources]
rag-core = { workspace = true }
app-layer-base = { git = "https://github.com/mjkimR/app-common.git", subdirectory = "app-layer-base", rev = "main" }
app-tools = { git = "https://github.com/mjkimR/app-common.git", subdirectory = "app-tools", rev = "main" }

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "app-tools",
]
