"""add error_message to knowledge_base_documents

Revision ID: 4ee4268018b4
Revises: 5c5bd237086c
Create Date: 2026-06-26 15:17:25.700777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee4268018b4'
down_revision: Union[str, None] = '5c5bd237086c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base_documents', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_base_documents', 'error_message')
    # ### end Alembic commands ###
