"""add group_id to job_process_histories

Revision ID: 5c5bd237086c
Revises: 2bc8fb5875da
Create Date: 2026-06-26 14:59:55.226462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5bd237086c'
down_revision: Union[str, None] = '2bc8fb5875da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_process_histories', sa.Column('group_id', sa.Uuid(), nullable=True))
    op.create_index('ix_job_process_histories_group_id', 'job_process_histories', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_process_histories_group_id', table_name='job_process_histories')
    op.drop_column('job_process_histories', 'group_id')
    # ### end Alembic commands ###
