"""add_temp_kb_tables

Revision ID: a5847a34ac23
Revises: de60cc736244
Create Date: 2026-06-22 10:09:28.046445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5847a34ac23'
down_revision: Union[str, None] = 'de60cc736244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_attachments',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_attachments_sha256'), 'file_attachments', ['sha256'], unique=True)
    op.create_table('session_file_attachments',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('file_attachment_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('processed_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_attachment_id'], ['file_attachments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'file_attachment_id', name='uq_thread_file_attachment')
    )
    op.create_index(op.f('ix_session_file_attachments_thread_id'), 'session_file_attachments', ['thread_id'], unique=False)
    op.create_table('session_knowledge_bases',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'knowledge_base_id', name='uq_thread_knowledge_base')
    )
    op.create_index(op.f('ix_session_knowledge_bases_thread_id'), 'session_knowledge_bases', ['thread_id'], unique=False)
    op.drop_column('ai_models', 'connection_mode')
    op.add_column('knowledge_bases', sa.Column('is_temp', sa.Boolean(), nullable=False))
    op.add_column('knowledge_bases', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'expires_at')
    op.drop_column('knowledge_bases', 'is_temp')
    op.add_column('ai_models', sa.Column('connection_mode', sa.VARCHAR(), server_default=sa.text("'gateway'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_session_knowledge_bases_thread_id'), table_name='session_knowledge_bases')
    op.drop_table('session_knowledge_bases')
    op.drop_index(op.f('ix_session_file_attachments_thread_id'), table_name='session_file_attachments')
    op.drop_table('session_file_attachments')
    op.drop_index(op.f('ix_file_attachments_sha256'), table_name='file_attachments')
    op.drop_table('file_attachments')
    # ### end Alembic commands ###
